config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
  get '/a-propos/presentation', to: 'a_propos#presentation', as: 'presentation'
  get '/a-propos/cv', to: 'a_propos#cv', as: 'cv'
  get '/a-propos/portfolio', to: 'a_propos#portfolio', as: 'portfolio'
  get '/projets', to: 'projets#index', as: 'projets'
  get '/services', to: 'services#index', as: 'services'
  get '/contacts', to: 'contacts#create', as: 'contacts'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :budget, presence: true, numericality: { greater_than: 0 }
  validates :asked_items, presence: true
  validates :start_time, presence: true
  validates :email, presence: true
  validates :informations, presence: true
end

app/controllers/a_propos_controller.rb
class AProposController < ApplicationController
  def presentation
  end

  def cv
  end

  def portfolio
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contact_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :brand, :website, :budget, :start_time, :deadline, :asked_items, :informations)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contact_path
      flash[:notice] = "Votre demande de contact est envoyé"
    else
      render :new, status: :unprocessable_entity
      flash[:error] = "Votre demande n'a pas pu être transmise"
    end
  end

  private

  def contact_params
    params.permit(:first_name, :last_name, :brand, :website, :budget, :start_time, :deadline, :asked_items, :informations)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/helpers/a_propos_helper.rb
module AProposHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/a_propos/cv.html.erb
<div class="cv-container">

  <div class="cv-content-container d-flex justify-content-between align-items-center flex-column">

    <div class="cv-header-container d-flex justify-content-center">

      <div class="cv-content-header d-flex justify-content-start">
        <h2>Mon CV</h2>
      </div>

    </div>

    <div class="cv-body d-flex">
      <span>Ajouter le contenu du CV dans cette div</span>
    </div>

    <div class="cta-portfolio d-flex justify-content-center">
      <%= link_to portfolio_path do %>
        <button class="btn btn-success">Voir mon portfolio</button>
      <% end %>
    </div>

  </div>

</div>

app/views/a_propos/presentation.html.erb
<div class="home-container">

  <div class="pres-container d-flex justify-content-around align-items-center">

    <div class="story-telling d-flex justify-content-center align-items-center">
      <p>une collaboration c’est aussi de l’humain donc l’idée ici c’est de faire du storytelling pour me presenter. dans l’objectif que la personne puisse voir si notre vision et vibes soient identiques pour que ça match</p>
    </div>

    <div class="introducing-myself d-flex justify-content-center align-items-center">
      <span>Vidéo de Duong So</span>
    </div>

    <div class="myself-in-words d-flex flex-column justify-content-center align-items-center">
      <p>mon why</p>
      <p>mon how</p>
      <p>mon what</p>
    </div>

    <div class="cta-cv d-flex justify-content-end">
      <%= link_to cv_path do %>
        <button class="btn btn-success">Voir mon CV</button>
      <% end %>
    </div>

  </div>

</div>

<div class="pres-stats-container">

  <div class="more-about-my-work">

    <div class="stats-container d-flex justify-content-start">

      <div class="my-stats d-flex justify-content-around align-items-center">

        <div class="stats-block d-flex flex-column justify-content-center align-items-center">
          <h3>Formation</h3>
          <div class="impact-text d-flex justify-content-center align-items-end mt-2">
            <h2>5</h2>
            <h5>ans</h5>
          </div>
        </div>

        <div class="stats-block d-flex flex-column justify-content-center align-items-center">
          <h3>Expériences</h3>
          <div class="impact-text d-flex justify-content-center align-items-end mt-2">
            <h2>10</h2>
            <h5>+</h5>
          </div>
        </div>

        <div class="stats-block d-flex flex-column justify-content-center align-items-center">
          <h3>Reels "Food"</h3>
          <div class="impact-text d-flex justify-content-center align-items-end mt-2">
            <h2>145</h2>
            <h5>+</h5>
          </div>
        </div>

        <div class="stats-block d-flex flex-column justify-content-center align-items-center">
          <h3>Abonnés</h3>
          <div class="impact-text d-flex justify-content-center align-items-end mt-2">
            <h2>17</h2>
            <h5>+</h5>
          </div>
        </div>

      </div>

    </div>

    <div class="cta-portfolio d-flex justify-content-center">
      <%= link_to portfolio_path do %>
        <button class="btn btn-success">Voir mon portfolio</button>
      <% end %>
    </div>

  </div>

</div>

<div class="pres-myself-container">

  <div class="more-about-me d-flex justify-content-around align-items-center">
    <h3>Ajouter plus de choses à propos de moi ou de mes envies</h3>
  </div>

</div>

<div class="pres-materials-container">

  <div class="materials-block d-flex flex-column justify-content-center align-items-center">

    <div class="materials-section  d-flex flex-column justify-content-between align-items-center">

      <div class="header-materials d-flex justify-content-start">
        <h2>Mon matériel Photo & Vidéo</h2>
      </div>

      <div class="materials-description-section d-flex justify-content-center align-items-center">
        <h3>tableau avec le matériel</h3>
      </div>

      <div class="follow-me-block d-flex flex-column align-items-center">
        <h2>Si tu veux encore plus de détails sur mes aventures, rejoins-moi ici:</h2>
        <div class="follow-links d-flex justify-content-center">
          <a href="https://www.tiktok.com/@guidebyso">Suis-moi <%= image_tag "https://static.vecteezy.com/ti/vecteur-libre/p1/6057996-logo-tiktok-sur-fond-transparent-gratuit-vectoriel.jpg" %></a>
          <a href="https://www.instagram.com/guidebyso/"><%= image_tag "https://cdn-icons-png.flaticon.com/512/174/174855.png" %> Suis-moi</a>
        </div>

      </div>

    </div>

  </div>

</div>

app/views/contacts/new.html.erb
<div class="contact-container">

  <div class="contact-section">

    <div class="thanks-contact">

    </div>

  </div>

</div>

<div class="contact-new">

  <div class="contact-new-section">

    <div class="contact-new-header">

      <h1>Saisir titre pour attirer sur le formulaire de demande de contact en dessous!</h1>

    </div>

    <div class="contact-new-body">

      <div class="form-contact-new">

        <%= simple_form_for(@contact) do |f| %>
          <%= f.input :first_name, label: false, placeholder: "Ton prénom" %>
          <%= f.input :last_name, label: false, placeholder: "Ton nom" %>
          <%= f.input :brand, label: false, placeholder: "Ta marque" %>
          <%= f.input :website, label: false, placeholder: "Ton site web ou tes réseaux" %>
          <%= f.input :budget, label: false, placeholder: "Ton budget" %>
          <%= f.input :start_time, label: "Dispo à partir du..." %>
          <%= f.input :deadline, label: "Terminé avant le..." %>
          <%= f.input :asked_items, label: false, placeholder: "Tu souhaites..." %>
          <%= f.input :informations, label: false, as: :text, placeholder: "Décris ta demande ici, essaie d'être le/la plus précis(e)" %>
          <button type="submit" class="btn btn-success">Envoyer la demande de contact</button>
        <% end %>

      </div>

    </div>

  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guide By So</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="scroll-box">
      <div class="scroll-box-block">
        <%= render "shared/navbar" %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="contact-container">

  <div class="contact-section">

    <div class="thanks-contact">

    </div>

  </div>

</div>

<div class="contact-new">

  <div class="contact-new-section">

    <div class="contact-new-header">

      <h1>Saisir titre pour attirer sur le formulaire de demande de contact en dessous!</h1>

    </div>

    <div class="contact-new-body">

      <div class="form-contact-new">

        <%= simple_form_for @contact do |f| %>
          <%= f.input :first_name, placeholder: "Prénom" %>
          <%= f.input :last_name, placeholder: "Nom" %>
          <%= f.input :brand, placeholder: "Marque" %>
          <%= f.input :website, placeholder: "Site web ou réseaux" %>
          <%= f.input :budget, placeholder: "Ton budget" %>
          <%= f.input :start_time, placeholder: "Dispo à partir de..." %>
          <%= f.input :deadline, placeholder: "Terminé avant le..." %>
          <%= f.input :asked_items, placeholder: "Tu souhaites..." %>
          <%= f.text :informations, placeholder: "Décris ta demande ici, essaie d'être le/la plus précis(e)" %>
          <%= f.submit "Envoyer " %>
          <%# <button type="submit" class="btn btn-success">Envoyer la demande de contact</button> %>
        <% end %>

      </div>

    </div>

  </div>



</div>

app/views/pages/home.html.erb
<div class="home-container">

  <div class="img-container">

    <h3>Phrase qui va avec la photo</h3>

    <div class="cta-services d-flex justify-content-center">
      <%= link_to services_path do %>
        <button class="btn btn-success">Voir mes services</button>
      <% end %>
    </div>

  </div>

</div>

<div class="home-content-container">

  <div class="short-presentation d-flex justify-content-around align-items-center">

    <p>Mini présentation de sophie duong</p>

    <div class="img-container">

    </div>

  </div>

</div>

<div class="home-content-container d-flex justify-content-center flex-column">

  <div class="last-content d-flex justify-content-center align-items-center">

    <div class="header-home-content d-flex justify-content-center align-items-center mb-4">
      <h3>Dernières créations de contenus</h3>
    </div>

    <div class="phone-block d-flex justify-content-around align-items-center">

      <div class="phone-case d-flex justify-content-center align-items-center">
        <span>IPhone</span>
      </div>

      <div class="phone-case d-flex justify-content-center align-items-center">
        <span>IPhone</span>
      </div>

      <div class="phone-case d-flex justify-content-center align-items-center">
        <span>IPhone</span>
      </div>

      <div class="phone-case d-flex justify-content-center align-items-center">
        <span>IPhone</span>
      </div>

    </div>

  </div>

</div>

<div class="home-content-container d-flex justify-content-center flex-column">

  <div class="trust-me d-flex justify-content-center align-items-center flex-column">

    <div class="header-home-content d-flex justify-content-center align-items-center mb-4">
      <h3>Ils m'ont fait confiance</h3>
    </div>

    <div class="rest-block d-flex justify-content-around align-items-center">

      <div class="project-link d-flex justify-content-center align-items-center">
        <%= link_to projets_path do %>
          <span>Mettre photo</span>
        <% end %>
      </div>

      <div class="project-link d-flex justify-content-center align-items-center">
        <%= link_to projets_path do %>
          <span>Mettre photo</span>
        <% end %>
      </div>

      <div class="project-link d-flex justify-content-center align-items-center">
        <%= link_to projets_path do %>
          <span>Mettre photo</span>
        <% end %>
      </div>

    </div>

    <div class="footer-home-content d-flex flex-column justify-content-center">
      <h3>C'est vous le prochain ?</h3>
      <button class="btn btn-success mt-2">Me contacter</button>
    </div>

  </div>

</div>

app/views/pages/services.html.erb
<div class="services-container">

  <div class="services-section">

    <div class="services-short-pres d-flex flex-column justify-content-around align-items-center">

      <div class="services-header d-flex justify-content-center align-items-center">
        <h2><strong>3 Services & Collab</strong></h2>
      </div>

      <div class="services-body d-flex justify-content-around align-items-center">

        <div class="service-item d-flex justify-content-center align-items-center">
          <h3><strong>Social Media</strong></h3>
        </div>

        <div class="service-item d-flex justify-content-center align-items-center">
          <h3>Création contenu <strong>Food</strong>, <strong>Activités</strong>, <strong>Expériences</strong> et <strong>Travel</strong></h3>
        </div>

        <div class="service-item d-flex justify-content-center align-items-center">
          <h3><strong>Contenu UGC</strong></h3>
        </div>

      </div>

    </div>

  </div>

</div>

<div class="other-service-container">

  <div class="other-service-section d-flex flex-column justify-content-center align-items-center">

    <div class="other-service-header d-flex justify-content-start align-items-center">
      <h2>Mes formules</h2>
    </div>

    <div class="other-service-body d-flex justify-content-center align-items-center">

      <div class="service-item-formula1 d-flex justify-content-center align-items-center text-align-center flex-column">
        <h2>Formule 1</h2>
        <span>Explication courte et brève de la première formule que je vous propose.</span>
        <span>Il s'agit de vous aider à améliorer chacun de ces points :</span>
        <p>☑ item 1</p>
        <p>☑ item 2</p>
        <p>☑ item 3</p>
        <p>☑ item 4</p>
        <p>☑ item 5</p>
      </div>

      <div class="service-item-formula2 d-flex justify-content-center align-items-center text-align-center flex-column">
        <h2>Formule 2</h2>
        <span>Explication courte et brève de la deuxième formule, mieux que la première que je vous propose.</span>
        <span>Il s'agit de vous aider à améliorer chacun de ces points :</span>
        <p>☑ item 1</p>
        <p>☑ item 2</p>
        <p>☑ item 3</p>
        <p>☑ item 4</p>
        <p>☑ item 5</p>
        <p>☑ item 6</p>
        <p>☑ item 7</p>
      </div>

      <div class="service-item-formula3 d-flex justify-content-center align-items-center text-align-center flex-column">
        <h2>Formule 3</h2>
        <span>Explication courte et brève de la troisième formule, la plus cccomplète que je vous propose et que vous trouverez sur le marché.</span>
        <span>Il s'agit de vous aider à améliorer chacun de ces points :</span>
        <p>☑ item 1</p>
        <p>☑ item 2</p>
        <p>☑ item 3</p>
        <p>☑ item 4</p>
        <p>☑ item 5</p>
        <p>☑ item 6</p>
        <p>☑ item 7</p>
        <p>☑ item 8</p>
        <p>☑ item 9</p>
        <p>☑ item 10</p>
      </div>

    </div>

    <div class="cta-contact d-flex justify-content-center">
      <%= link_to contact_path do %>
        <button class="btn btn-success">Me contacter</button>
      <% end %>
    </div>

  </div>

</div>

app/views/services/index.html.erb
<div class="services-container">

  <div class="services-section">

    <div class="services-short-pres d-flex flex-column justify-content-around align-items-center">

      <div class="services-header d-flex justify-content-center align-items-center">
        <h2><strong>3 Services & Collab</strong></h2>
      </div>

      <div class="services-body d-flex justify-content-around align-items-center">

        <div class="service-item d-flex justify-content-center align-items-center">
          <h3><strong>Social Media</strong></h3>
        </div>

        <div class="service-item d-flex justify-content-center align-items-center">
          <h3>Création contenu <strong>Food</strong>, <strong>Activités</strong>, <strong>Expériences</strong> et <strong>Travel</strong></h3>
        </div>

        <div class="service-item d-flex justify-content-center align-items-center">
          <h3><strong>Contenu UGC</strong></h3>
        </div>

      </div>

    </div>

  </div>

</div>

<div class="other-service-container">

  <div class="other-service-section d-flex flex-column justify-content-center align-items-center">

    <div class="other-service-header d-flex justify-content-start align-items-center">
      <h2>Mes formules</h2>
    </div>

    <div class="other-service-body d-flex justify-content-center align-items-center">

      <div class="service-item-formula1 d-flex justify-content-center align-items-center text-align-center flex-column">
        <h2>Formule 1</h2>
        <span>Explication courte et brève de la première formule que je vous propose.</span>
        <span>Il s'agit de vous aider à améliorer chacun de ces points :</span>
        <p>☑ item 1</p>
        <p>☑ item 2</p>
        <p>☑ item 3</p>
        <p>☑ item 4</p>
        <p>☑ item 5</p>
      </div>

      <div class="service-item-formula2 d-flex justify-content-center align-items-center text-align-center flex-column">
        <h2>Formule 2</h2>
        <span>Explication courte et brève de la deuxième formule, mieux que la première que je vous propose.</span>
        <span>Il s'agit de vous aider à améliorer chacun de ces points :</span>
        <p>☑ item 1</p>
        <p>☑ item 2</p>
        <p>☑ item 3</p>
        <p>☑ item 4</p>
        <p>☑ item 5</p>
        <p>☑ item 6</p>
        <p>☑ item 7</p>
      </div>

      <div class="service-item-formula3 d-flex justify-content-center align-items-center text-align-center flex-column">
        <h2>Formule 3</h2>
        <span>Explication courte et brève de la troisième formule, la plus cccomplète que je vous propose et que vous trouverez sur le marché.</span>
        <span>Il s'agit de vous aider à améliorer chacun de ces points :</span>
        <p>☑ item 1</p>
        <p>☑ item 2</p>
        <p>☑ item 3</p>
        <p>☑ item 4</p>
        <p>☑ item 5</p>
        <p>☑ item 6</p>
        <p>☑ item 7</p>
        <p>☑ item 8</p>
        <p>☑ item 9</p>
        <p>☑ item 10</p>
      </div>

    </div>

    <div class="cta-contact d-flex justify-content-center">
      <%= link_to contacts_path do %>
        <button class="btn btn-success">Me contacter</button>
      <% end %>
    </div>

  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="top-home-gbs navbar-expand-sm navbar-light d-flex flex-column justify-content-center align-items-center">

  <div class="redirect-logos d-flex justify-content-center align-items-center">

    <a href="https://www.tiktok.com/@guidebyso"><%= image_tag "https://static.vecteezy.com/ti/vecteur-libre/p1/6057996-logo-tiktok-sur-fond-transparent-gratuit-vectoriel.jpg" %></a>

    <a href="https://www.instagram.com/guidebyso/"><%= image_tag "https://cdn-icons-png.flaticon.com/512/174/174855.png" %></a>

    <a href="https://www.facebook.com/profile.php?id=100079345668453"><%= image_tag "https://cdn-icons-png.flaticon.com/256/124/124010.png" %></a>

    <a href="https://mapstr.com/user/guidebyso"><%= image_tag "https://play-lh.googleusercontent.com/5PNPvDqjHmvEZpr-2KaGDF62AckPANQWr8vko6ha0aoZ1f8x_tFNcEHLMTcTCrLyqg" %></a>

  </div>

  <div class="navbar">

    <div class="logo-gbs d-flex justify-content-center">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ClmtMlt" %>
      <% end %>
    </div>

    <div class="actions-menu-gbs d-flex justify-content-center">

      <ul class="navbar-nav me-auto d-flex justify-content-around">

        <li class="nav-item active">
          <%= link_to "ACCUEIL", root_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <p class="avatar dropdown-toggle nav-link" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">À PROPOS</p>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "PRÉSENTATION", presentation_path, class: "dropdown-item" %>
            <%= link_to "CV", cv_path, class: "dropdown-item" %>
            <%= link_to "PORTFOLIO", portfolio_path, class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to "PROJETS", projets_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "SERVICES", services_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "CONTACT", contacts_path, class: "nav-link" %>
        </li>

      </ul>

    </div>

  </div>

</div>